defaults:
  - default

_target_: model.regression.RegressionModel

lambda: 1
loss: null

metrics: null
  #Dice:
  #  _target_: monai.metrics.DiceMetric
  #  include_background: false
  #ASD:
  #  _target_: monai.metrics.SurfaceDistanceMetric
  #  include_background: false
  #mIoU:
  #  _target_: monai.metrics.ConfusionMatrixMetric
  #  include_background: false
  #  metric_name: threat score
  #F1:
  #  _target_: monai.metrics.ConfusionMatrixMetric
  #  include_background: true
  #  metric_name: f1
  #MAE:
  #  _target_: monai.metrics.MAEMetric

inferer: null