base:
  spatial_dims: ${data.dataset.spatial_dims}
  in_channels: ${data.dataset.image_channels}

netA:
  _target_: mislight.networks.nets.convnext.ConvNeXtBN
  model_name: convnext_pico
  spatial_dims: ${..base.spatial_dims}
  in_channels: ${..base.in_channels}
  num_classes: ${data.dataset.num_classes}